### ISSUE TITLE
Unrecognized field "householdId" on CreativeTonie

### ISSUE THREAD

**Issue by mrad86** [maximilianvoss/toniebox-api#3]
It looks like the API was updated again and this field is missing:

`ERROR:rocks.voss.spotifytonieboxsync.Application:main:71: IOException
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "householdId" (class rocks.voss.toniebox.beans.toniebox.CreativeTonie), not marked as ignorable (12 known properties: , "private", "chapters", "name", "live", "chaptersRemaining", "transcoding", "imageUrl", "chaptersPresent", "secondsRemaining", "id", "secondsPresent", "transcodingErrors"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: rocks.voss.toniebox.beans.toniebox.CreativeTonie["householdId"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:1902)
        at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:23)
        at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:16)
        at rocks.voss.toniebox.RequestHandler.executeRequest(RequestHandler.java:159)
        at rocks.voss.toniebox.RequestHandler.executeGetRequest(RequestHandler.java:111)
        at rocks.voss.toniebox.RequestHandler.getCreativeTonies(RequestHandler.java:60)
        at rocks.voss.toniebox.TonieHandler.getCreativeTonies(TonieHandler.java:64)
        at rocks.voss.spotifytonieboxsync.Application.main(Application.java:63)`

**Comment by paschmal** [comment]
I just run into the same issue. Please see my fix #4

**Comment by mrad86** [comment]
Thank you for the quick fix!

**Comment by ju5tler** [comment]
I still get this error, even when I use the fork of toniebox-api from @paschmal for my build (with jitpack). 

Might be me, not really a Developer. But it used the code from the latest commit.

**Comment by maximilianvoss** [comment]
@ju5tler you have to build the source from scratch or use the latest release which is available to not have this issue anymore
