### ISSUE TITLE
compatibility with SSO login

### ISSUE THREAD

**Issue by moritzj29** [maximilianvoss/toniebox-api#5]
Hi,
I tried setting up the toniebox sync this weekend and stumbled upon an error with the spotify-toniebox-sync v1.3 and 2.0. To trace down the error I also tried the example code for the toniebox API, resulting in the same error:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "errors" (class rocks.voss.toniebox.beans.toniebox.JWTToken), not marked as ignorable (one known property: "jwt"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: rocks.voss.toniebox.beans.toniebox.JWTToken["errors"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:1902)
	at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:25)
	at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:17)
	at rocks.voss.toniebox.RequestHandler.executeRequest(RequestHandler.java:159)
	at rocks.voss.toniebox.RequestHandler.executePostRequest(RequestHandler.java:125)
	at rocks.voss.toniebox.RequestHandler.Login(RequestHandler.java:48)
	at rocks.voss.toniebox.TonieHandler.login(TonieHandler.java:43)
	at rocks.voss.toniebox.example.Application.main(Application.java:21)
```
The returned json passed to the ObjectMapper is: `{"errors": [{"code": "ssoAuthRequired", "key": "email"}]}`

Apparently, the toniecloud requires some single sign-on? There were some changes during the last weeks, where the accounts for the toniecloud and the shop were merged (https://support.tonies.com/hc/de/articles/360014603439). I got an email about this on 19th of August.
Probably this is related? Is anybody else experiencing difficulties?

Unfortunately my Java skills are non existent, so I don't see how I could fix this myself. But I'm very happy to assist wherever I can with logs/debugging/... .

(Previously mentioned here, but moved https://github.com/maximilianvoss/spotify-toniebox-sync/issues/11)

**Comment by cachapa** [comment]
I'm running into the same problem with my package: https://github.com/cachapa/tonie_shuffle

It seems they've switched to using KeyCloak and/or OpenID for their login process. I've tried inspecting the network traffic using the Chrome dev tools but haven't been able to get much further than a 400 or 403.

**Comment by cachapa** [comment]
It seems the CreativeManager project managed to implement the new SSO: https://github.com/mwinkler/TonieBox.CreativeManager/commit/665f8e390df88587ecb41c2c413637cac38fa573

**Comment by cachapa** [comment]
Update: I managed to implement the new SSO in tonie_suffle. My implementation is slightly more efficient than the CreativeManager one since it calls the KeyCloak `token` endpoint directly instead of emulating the browser process.

Here's my implementation: https://github.com/cachapa/tonie_shuffle/commit/d92731b1461fab73f0758f15eb24c015c8becbb7#diff-d2614d4c644c0852ab8d24fb4f177e77

**Comment by maximilianvoss** [comment]
thanks for the PR
